#!/usr/bin/env python3
"""Quarantine artifacts that were accidentally generated in a parent folder."""
from __future__ import annotations

import argparse
import shutil
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from qt611_project_utils import find_project_root  # noqa: E402


@dataclass
class ActionLog:
    outer: Path
    project: Path
    apply: bool
    quarantine: Path
    actions: list[str]

    def add(self, text: str) -> None:
        self.actions.append(text)

    def move(self, path: Path, reason: str) -> None:
        if not path.exists():
            return
        try:
            path.relative_to(self.project)
            self.add(f"skip project-owned path: {path}")
            return
        except ValueError:
            pass
        rel = path.relative_to(self.outer)
        target = self.quarantine / rel
        suffix = 1
        while target.exists():
            target = self.quarantine / f"{rel.name}.{suffix}"
            suffix += 1
        self.add(f"quarantine {reason}: {path} -> {target}")
        if self.apply:
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.move(str(path), str(target))


def text_contains(path: Path, needles: list[str]) -> bool:
    try:
        text = path.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return False
    return any(n in text for n in needles)


def looks_like_generated_cmakelists(path: Path) -> bool:
    return text_contains(path, ["Qt 6.11", "qt_add_qml_module", "Generated by", "Qt611"])


def looks_like_stray_kit_dir(path: Path) -> bool:
    if not path.is_dir() or (path / "pyproject.toml").exists():
        return False
    markers = ["template_cpp_qml", "template_rust_cxx_qt", "transpiled_examples"]
    if any((path / marker).exists() for marker in markers):
        return True
    if (path / "scripts" / "continue_qt611_transpile.py").exists():
        return True
    return False


def cleanup(outer: Path, project: Path, apply: bool, quarantine_stray_kit_dirs: bool) -> ActionLog:
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    log = ActionLog(
        outer=outer,
        project=project,
        apply=apply,
        quarantine=outer / ".qt611_misroot_quarantine" / timestamp,
        actions=[],
    )

    if outer == project:
        log.add("input root already is the project root; no parent-folder quarantine needed")
        return log

    for child in sorted(outer.iterdir()):
        if child == project:
            continue
        name = child.name
        if name == ".qt611_misroot_quarantine":
            log.add(f"keep existing quarantine directory: {child}")
        elif name.startswith(".qt611") or name in {"legacy_slint", "legacy_build_metadata"}:
            log.move(child, "migration backup/report directory")
        elif name in {"qml", "cpp"}:
            log.move(child, "generated top-level Qt directory outside the real project")
        elif name == "CMakeLists.txt" and child.is_file() and looks_like_generated_cmakelists(child):
            log.move(child, "generated top-level CMakeLists.txt outside the real project")
        elif name == "src" and child.is_dir() and (child / "backend.rs").exists() and not (child / "notizen_py_qt").exists():
            log.move(child, "generated top-level src directory outside the real project")
        elif name.startswith("QT611_") and name.endswith(".md"):
            log.move(child, "stale parent-folder migration report")
        elif quarantine_stray_kit_dirs and looks_like_stray_kit_dir(child):
            log.move(child, "stray migration kit/template directory outside the real project")

    if not log.actions:
        log.add("no parent-folder artifacts found")
    return log


def write_report(log: ActionLog) -> None:
    report = log.project / "QT611_MISROOT_RECOVERY.md"
    lines = [
        "# Qt 6.11 parent-folder recovery",
        "",
        f"Mode: {'APPLY' if log.apply else 'DRY-RUN'}",
        f"Outer root: `{log.outer}`",
        f"Detected project root: `{log.project}`",
        f"Quarantine: `{log.quarantine}`",
        "",
        "## Actions",
        "",
    ]
    lines.extend(f"- {a}" for a in log.actions)
    if log.apply:
        report.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines + [f"- {a}" for a in []]))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Quarantine artifacts from an accidental parent-folder migration run")
    parser.add_argument("root", nargs="?", default=".")
    parser.add_argument("--project-root", help="Override detected project root")
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--quarantine-stray-kit-dirs", action="store_true")
    args = parser.parse_args(argv)

    outer = Path(args.root).resolve()
    project = Path(args.project_root).resolve() if args.project_root else find_project_root(outer)
    log = cleanup(outer, project, args.apply, args.quarantine_stray_kit_dirs)

    print(f"Mode: {'APPLY' if args.apply else 'DRY-RUN'}")
    print(f"Outer root: {outer}")
    print(f"Detected project root: {project}")
    for action in log.actions:
        print(f"- {action}")

    if args.apply:
        report = project / "QT611_MISROOT_RECOVERY.md"
        lines = [
            "# Qt 6.11 parent-folder recovery",
            "",
            f"Mode: APPLY",
            f"Outer root: `{outer}`",
            f"Detected project root: `{project}`",
            f"Quarantine: `{log.quarantine}`",
            "",
            "## Actions",
            "",
            *[f"- {a}" for a in log.actions],
            "",
        ]
        report.write_text("\n".join(lines), encoding="utf-8")
        print(f"Wrote report: {report}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
