"""Python/Qt continuation port of the legacy Notizen.NET application."""

from .models import (
    DesktopNoteState,
    NoteDocument,
    NoteNode,
    legacy_delete_fallback_node,
    legacy_new_next_node,
    legacy_new_next_parent,
    legacy_can_move_before_target,
    legacy_move_before_target,
    legacy_paste_clone,
    legacy_previous_visible_node,
    legacy_visible_walk,
)
from .alx_io import backup_directory_for, create_backup, dump_alx_bytes, list_backups, load_alx, load_alx_bytes, save_alx
from .settings import (
    LEGACY_RECENT_FILE_SLOTS,
    legacy_activate_recent_file,
    legacy_autosave_should_save,
    legacy_recent_files_from_slots,
    legacy_recent_slots_from_files,
    legacy_remember_recent_file,
    normalize_autosave_seconds,
    normalize_window_state,
)
from .tray_support import decide_startup_tray_visibility, is_gnome_session
from .startup import StartupTargetValidation, build_autostart_command, legacy_autostart_arguments, validate_legacy_startup_target
from .desktop_note_legacy import (
    LEGACY_DESKNOTE_AUTORESIZE_IDLE_MS,
    LEGACY_DESKNOTE_AUTORESIZE_SCROLL_PAD,
    LEGACY_DESKNOTE_AUTORESIZE_STEP,
    LEGACY_DESKNOTE_AUTORESIZE_WORK_AREA_PAD,
    LEGACY_DESKNOTE_MIN_AUTOSIZE_HEIGHT,
    LegacyDeskNoteCursor,
    LegacyDeskNoteMouseAction,
    LegacyDeskNoteRect,
    legacy_desknote_auto_resize_can_grow,
    legacy_desknote_auto_resize_grow_both_step,
    legacy_desknote_auto_resize_grow_width_step,
    legacy_desknote_auto_resize_shrink_step,
    legacy_desknote_clamp_to_work_area,
    legacy_desknote_cursor_for_move_action,
    legacy_desknote_editor_rect,
    legacy_desknote_hidden_border_geometry,
    legacy_desknote_hover_geometry,
    legacy_desknote_label_geometry,
    legacy_desknote_mouse_down_action,
    legacy_desknote_mouse_move_action,
    legacy_desknote_move_geometry,
    legacy_desknote_opacity_for_active,
    legacy_desknote_opacity_for_inactive,
    legacy_desknote_point_outside,
    legacy_desknote_resize_geometry,
    legacy_desknote_show2_geometry,
    legacy_desknote_title_hit_action,
    legacy_opacity_percent_for_transparency_percent,
    legacy_transparency_menu_options,
)
from .legacy_paths import LEGACY_DEFAULT_FILENAME, legacy_documents_notizen_dir, split_legacy_file_location
from .search_results import SearchHitView, build_search_hit_views, legacy_search_result_label, legacy_search_snippet, node_path
from .editor_legacy import legacy_clipboard_bullet_text, qt_bullet_insert_text
from .rtf_utils import (
    LEGACY_OBJECT_PLACEHOLDER,
    RtfHyperlink,
    bmp_to_dib_bytes,
    dib_to_bmp_bytes,
    html_to_rtf,
    rtf_ansi_encoding,
    rtf_to_html,
    rtf_to_plain_text,
)
from .window_visibility import VisibleWindowGeometry, env_requests_window_reset, legacy_window_state_is_restorable, sanitize_legacy_window_geometry, should_start_minimized
from .display_env import DisplayEnvironmentDecision, apply_graphical_session_environment, normalize_qt_display_environment, visible_start_requested
from .i18n import (
    LEGACY_LANGUAGE_KEY_ORDER,
    available_languages,
    legacy_language_key_for_index,
    legacy_language_translations,
    resolve_language,
    tr,
)
from .alarms import (
    LEGACY_WECKER_WEEKDAY_CHECKBOXES,
    legacy_wecker_interval_unit,
    legacy_wecker_weekday_for_checkbox,
    legacy_wecker_weekday_labels,
)
from .keyboard_legacy import LegacyShortcut, legacy_shortcut_action
from .feedback import (
    FeedbackDecision,
    FeedbackThrottleState,
    dotnet_date_ticks,
    legacy_feedback_decision,
    legacy_feedback_filename,
    legacy_feedback_next_state,
    legacy_feedback_text_is_long_enough,
    write_local_feedback_archive,
)
from .system_integration import (
    LEGACY_ALX_EXTENSION,
    LEGACY_ALX_PROG_ID,
    WindowsRegistryEntry,
    build_linux_desktop_exec,
    build_windows_module_open_command,
    build_windows_script_open_command,
    legacy_windows_alx_registry_entries,
    quote_windows_argument,
    windows_association_preview_lines,
)
from .legacy_validation import (
    LegacyAlxRoundtripResult,
    LegacyAlxSummary,
    summarize_alx_bytes,
    summarize_alx_file,
    summarize_document,
    validate_alx_roundtrip_bytes,
    validate_alx_roundtrip_file,
)

__all__ = [
    "DesktopNoteState",
    "NoteDocument",
    "NoteNode",
    "legacy_paste_clone",
    "legacy_new_next_parent",
    "legacy_new_next_node",
    "legacy_can_move_before_target",
    "legacy_move_before_target",
    "legacy_visible_walk",
    "legacy_previous_visible_node",
    "legacy_delete_fallback_node",
    "backup_directory_for",
    "create_backup",
    "list_backups",
    "load_alx",
    "load_alx_bytes",
    "dump_alx_bytes",
    "save_alx",
    "normalize_autosave_seconds",
    "legacy_autosave_should_save",
    "normalize_window_state",
    "LEGACY_RECENT_FILE_SLOTS",
    "legacy_recent_files_from_slots",
    "legacy_recent_slots_from_files",
    "legacy_remember_recent_file",
    "legacy_activate_recent_file",
    "decide_startup_tray_visibility",
    "is_gnome_session",
    "legacy_opacity_percent_for_transparency_percent",
    "legacy_transparency_menu_options",
    "LEGACY_DESKNOTE_AUTORESIZE_IDLE_MS",
    "LEGACY_DESKNOTE_AUTORESIZE_SCROLL_PAD",
    "LEGACY_DESKNOTE_AUTORESIZE_STEP",
    "LEGACY_DESKNOTE_AUTORESIZE_WORK_AREA_PAD",
    "LEGACY_DESKNOTE_MIN_AUTOSIZE_HEIGHT",
    "LegacyDeskNoteMouseAction",
    "LegacyDeskNoteCursor",
    "LegacyDeskNoteRect",
    "legacy_desknote_auto_resize_can_grow",
    "legacy_desknote_auto_resize_grow_both_step",
    "legacy_desknote_auto_resize_grow_width_step",
    "legacy_desknote_auto_resize_shrink_step",
    "legacy_desknote_hover_geometry",
    "legacy_desknote_hidden_border_geometry",
    "legacy_desknote_opacity_for_active",
    "legacy_desknote_opacity_for_inactive",
    "legacy_desknote_title_hit_action",
    "legacy_desknote_show2_geometry",
    "legacy_desknote_editor_rect",
    "legacy_desknote_label_geometry",
    "legacy_desknote_mouse_down_action",
    "legacy_desknote_mouse_move_action",
    "legacy_desknote_cursor_for_move_action",
    "legacy_desknote_move_geometry",
    "legacy_desknote_resize_geometry",
    "legacy_desknote_clamp_to_work_area",
    "legacy_desknote_point_outside",
    "LEGACY_DEFAULT_FILENAME",
    "legacy_documents_notizen_dir",
    "split_legacy_file_location",
    "build_autostart_command",
    "legacy_autostart_arguments",
    "StartupTargetValidation",
    "validate_legacy_startup_target",
    "legacy_clipboard_bullet_text",
    "qt_bullet_insert_text",
    "node_path",
    "legacy_search_snippet",
    "legacy_search_result_label",
    "build_search_hit_views",
    "SearchHitView",
    "bmp_to_dib_bytes",
    "dib_to_bmp_bytes",
    "rtf_ansi_encoding",
    "rtf_to_plain_text",
    "rtf_to_html",
    "html_to_rtf",
    "RtfHyperlink",
    "LEGACY_OBJECT_PLACEHOLDER",
    "VisibleWindowGeometry",
    "sanitize_legacy_window_geometry",
    "legacy_window_state_is_restorable",
    "should_start_minimized",
    "env_requests_window_reset",
    "DisplayEnvironmentDecision",
    "apply_graphical_session_environment",
    "normalize_qt_display_environment",
    "visible_start_requested",
    "legacy_language_translations",
    "legacy_language_key_for_index",
    "LEGACY_LANGUAGE_KEY_ORDER",
    "available_languages",
    "resolve_language",
    "tr",
    "LEGACY_WECKER_WEEKDAY_CHECKBOXES",
    "legacy_wecker_weekday_for_checkbox",
    "legacy_wecker_weekday_labels",
    "legacy_wecker_interval_unit",
    "LegacyShortcut",
    "legacy_shortcut_action",
    "LegacyAlxSummary",
    "LegacyAlxRoundtripResult",
    "summarize_document",
    "summarize_alx_bytes",
    "summarize_alx_file",
    "validate_alx_roundtrip_bytes",
    "validate_alx_roundtrip_file",
    "FeedbackDecision",
    "FeedbackThrottleState",
    "dotnet_date_ticks",
    "legacy_feedback_decision",
    "legacy_feedback_filename",
    "legacy_feedback_next_state",
    "legacy_feedback_text_is_long_enough",
    "write_local_feedback_archive",
    "LEGACY_ALX_EXTENSION",
    "LEGACY_ALX_PROG_ID",
    "WindowsRegistryEntry",
    "build_linux_desktop_exec",
    "build_windows_module_open_command",
    "build_windows_script_open_command",
    "legacy_windows_alx_registry_entries",
    "quote_windows_argument",
    "windows_association_preview_lines",
]

__version__ = "0.10.19"
